Revert "change Sed pattern"
This reverts commit f59b628cebf7232d64ea84c15098f954b1709758.

diff --git a/.github/workflows/build-RootActivityLauncher.yaml b/.github/workflows/build-RootActivityLauncher.yaml
--- a/.github/workflows/build-RootActivityLauncher.yaml
+++ b/.github/workflows/build-RootActivityLauncher.yaml
@@ -1,2 +1,89 @@
-          APP_ID=$(awk -F '"' '/applicationId( |=)/ {print $2; exit}' $BUILD_GRADLE)
-          sed -E "/applicationId( |=)/s|${APP_ID}|${NEW_APP_ID}|" -i $BUILD_GRADLE
+name: Build - RootActivityLauncher
+
+on:
+  workflow_dispatch:
+
+env:
+  APP_NAME: "RootActivityLauncher"
+  APK_PATH_PREFIX: "app/build/outputs/apk/release"
+  NEW_APP_ID: 'bff.rootactivitylauncher'
+  FLAV: ""
+
+jobs:
+  build:
+    runs-on: ubuntu-latest # Use the latest Ubuntu runner
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: "zacharee/RootActivityLauncher"
+          ref: "master"
+
+      - uses: actions/setup-java@v4
+        with:
+          java-version: "17"
+          distribution: "temurin"
+          cache: "gradle" # Cache Gradle dependencies to speed up builds
+
+      - name: Download and Install Modified Android JARs
+        run: |
+          # see https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
+          # for pre-defined Environment variables (i.e. ANDROID_HOME, ANDROID_SDK_ROOT)
+
+          API_LEVEL=$(curl -sL https://raw.githubusercontent.com/zacharee/RootActivityLauncher/refs/heads/master/app/build.gradle.kts | awk '/compileSdk/ {print $NF; exit}')
+          echo ${API_LEVEL} | grep -E '^[0-9]+$' || exit 1
+
+          TARGET_DIR="$ANDROID_SDK_ROOT/platforms/android-${API_LEVEL}"
+
+          # Create the target directory if it doesn't exist
+          mkdir -p "$TARGET_DIR" || { echo "Failed to create directory $TARGET_DIR"; exit 1; }
+
+          # Download the modified android.jar from Reginer/aosp-android-jar
+          curl -L -o "$TARGET_DIR/android.jar" "https://github.com/Reginer/aosp-android-jar/raw/refs/heads/main/android-${API_LEVEL}/android.jar"
+          [[ $? -ne 0 ]] && exit 1
+          echo "android.jar downloaded successfully."
+
+      - name: Change versionCode To Max INT
+        run: >
+              sed -E '/^\s*versionCode/s/[0-9]+$/2147483647/' -i app/build.gradle || \
+              sed -E '/^\s*versionCode/s/[0-9]+$/2147483647/' -i app/build.gradle.kts
+      
+      - name: Change app and package name
+        run: >
+          BUILD_GRADLE=$(find app -maxdepth 1 -name 'build.gradle' -or -name 'build.gradle.kts')
+          APP_ID=$(awk -F '"' '/applicationId / {print $2; exit}' $BUILD_GRADLE)
+          sed -E "/applicationId /s|${APP_ID}|${NEW_APP_ID}|" -i $BUILD_GRADLE
+
+      - name: Build with Gradle
+        run: |
+          chmod +x gradlew
+          ./gradlew :app:assembleRelease
+
+      - name: List APKs
+        run: find . -name '*.apk'
+
+      # - name: Upload APK artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: RootActivityLauncher-APK                 # Name of the artifact
+      #     path: app/build/outputs/apk/release/*.apk     # Path to the release APK files
+      #     retention-days: 5                             # Keep the artifact for 5 days
+
+      - name: Sign APK
+        env:
+          KEYSTORE: ${{ secrets.SIGNING_KEY }}
+          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
+        run: |
+          versionName=$( jq -r '.elements[0].versionName' ${APK_PATH_PREFIX}/output-metadata.json )
+          echo "${KEYSTORE}" | base64 -d > apksign.keystore
+          for apk in ${APK_PATH_PREFIX}/*.apk; do ${ANDROID_HOME}/build-tools/34.0.0/apksigner sign --ks apksign.keystore --ks-pass env:SIGNING_STORE_PASSWORD $apk; done
+
+      - name: Release
+        env:
+          GH_TOKEN: ${{ secrets.GH_APK_REPO }}
+          # GH_TOKEN: ${{ github.token }}
+        run: |
+          versionName=$( jq -r '.elements[0].versionName' ${APK_PATH_PREFIX}/output-metadata.json )
+          gh release create "${versionName}-${APP_NAME}" --title "${APP_NAME} ${versionName}" --repo wrppg/apk ${APK_PATH_PREFIX}/*.apk
+
+          # gh release upload "${versionName}-${APP_NAME}" ${APK_PATH_PREFIX}/*.apk
